# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cosmetic_app.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("NanumBarunGothic")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(0, 0, 1440, 1080))
        self.camera.setStyleSheet("image: url(:/newPrefix/camera.png);")
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.back_1 = QtWidgets.QLabel(self.centralwidget)
        self.back_1.setGeometry(QtCore.QRect(40, 861, 180, 180))
        self.back_1.setStyleSheet("image: url(:/newPrefix/back.png);")
        self.back_1.setText("")
        self.back_1.setObjectName("back_1")
        self.back_2 = QtWidgets.QLabel(self.centralwidget)
        self.back_2.setGeometry(QtCore.QRect(250, 861, 180, 180))
        self.back_2.setStyleSheet("image: url(:/newPrefix/back.png);")
        self.back_2.setText("")
        self.back_2.setObjectName("back_2")
        self.face = QtWidgets.QLabel(self.centralwidget)
        self.face.setGeometry(QtCore.QRect(40, 861, 180, 180))
        self.face.setStyleSheet("image: url(:/newPrefix/person_0.png);")
        self.face.setText("")
        self.face.setObjectName("face")
        self.cosmetic = QtWidgets.QLabel(self.centralwidget)
        self.cosmetic.setGeometry(QtCore.QRect(250, 861, 180, 180))
        self.cosmetic.setStyleSheet("image: url(:/newPrefix/cosmetic_0.png);")
        self.cosmetic.setText("")
        self.cosmetic.setObjectName("cosmetic")
        self.pink_gradient = QtWidgets.QLabel(self.centralwidget)
        self.pink_gradient.setGeometry(QtCore.QRect(0, 0, 1440, 1080))
        self.pink_gradient.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(255, 255, 255, 0), stop:1 rgba(255, 0, 48, 150));")
        self.pink_gradient.setText("")
        self.pink_gradient.setObjectName("pink_gradient")
        self.detection = QtWidgets.QLabel(self.centralwidget)
        self.detection.setGeometry(QtCore.QRect(296, 310, 848, 460))
        self.detection.setStyleSheet("image: url(:/newPrefix/detection.png);")
        self.detection.setText("")
        self.detection.setObjectName("detection")
        self.text_1 = QtWidgets.QLabel(self.centralwidget)
        self.text_1.setGeometry(QtCore.QRect(302, 89, 836, 58))
        font = QtGui.QFont()
        font.setFamily("NanumBarunGothic")
        font.setPointSize(50)
        font.setBold(False)
        font.setWeight(50)
        self.text_1.setFont(font)
        self.text_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.text_1.setObjectName("text_1")
        self.text_2 = QtWidgets.QLabel(self.centralwidget)
        self.text_2.setEnabled(True)
        self.text_2.setGeometry(QtCore.QRect(350, 155, 740, 69))
        font = QtGui.QFont()
        font.setFamily("NanumBarunGothic")
        font.setPointSize(60)
        font.setBold(False)
        font.setWeight(50)
        self.text_2.setFont(font)
        self.text_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.text_2.setObjectName("text_2")
        self.barcode = QtWidgets.QLabel(self.centralwidget)
        self.barcode.setGeometry(QtCore.QRect(1570, 475, 220, 205))
        self.barcode.setStyleSheet("image: url(:/newPrefix/barcode.png);")
        self.barcode.setText("")
        self.barcode.setObjectName("barcode")
        self.barcode_2 = QtWidgets.QLabel(self.centralwidget)
        self.barcode_2.setGeometry(QtCore.QRect(1497, 399, 366, 46))
        font = QtGui.QFont()
        font.setFamily("NanumBarunGothic")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.barcode_2.setFont(font)
        self.barcode_2.setStyleSheet("color: rgb(189, 189, 189);")
        self.barcode_2.setObjectName("barcode_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_1.setText(_translate("MainWindow", "당신과 가장 어울리는 컬러를 찾아볼까요?"))
        self.text_2.setText(_translate("MainWindow", "얼굴과 화장품을 인식해주세요."))
        self.barcode_2.setText(_translate("MainWindow", "바코드를 스캔해주세요"))

import source

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

